#pragma once

static const char * const weekday_names_sk[7] = {
  "Nedela",
  "Pondelok",
  "Utorok",
  "Streda",
  "Stvrtok",
  "Piatok",
  "Sobota"
};

static const char * const calendar_names_sk[12][31] = {
  { // januar
    "Novy rok",
    "Alexandra, Karina",
    "Daniela",
    "Drahoslav",
    "Andrea",
    "Antonia",
    "Bohuslava",
    "Severin",
    "Alexej",
    "Dasa",
    "Malvina",
    "Ernest",
    "Rastislav",
    "Radovan",
    "Dobroslava, Dobroslav",
    "Kristina",
    "Natasa",
    "Bohdana",
    "Mario",
    "Dalibor, Sebastian",
    "Vincent",
    "Zora",
    "Milos",
    "Timotej",
    "Gejza",
    "Tamara",
    "Bohus",
    "Alfonz",
    "Gaspar",
    "Ema",
    "Emil",
  }, { // februar
    "Tatiana",
    "Erika, Erik",
    "Blazej",
    "Veronika",
    "Agata",
    "Dorota",
    "Vanda",
    "Zoja",
    "Zdenko",
    "Gabriela",
    "Dezider",
    "Perla",
    "Arpad",
    "Valentin",
    "Pravoslav",
    "Ida, Liana",
    "Miloslava",
    "Jaromir",
    "Vlasta",
    "Livia",
    "Eleonora",
    "Etela",
    "Roman, Romana",
    "Matej, Mateo",
    "Frederik, Frederika",
    "Viktor",
    "Alexander",
    "Zlatica",
    "Radomir",
  }, { // marec
    "Albin",
    "Anezka",
    "Bohumil, Bohumila",
    "Kazimir",
    "Fridrich",
    "Radoslav, Radoslava",
    "Tomas",
    "Alan, Alana",
    "Frantiska",
    "Bruno, Branislav",
    "Angela, Angelika",
    "Gregor",
    "Vlastimil",
    "Matilda",
    "Svetlana",
    "Boleslav",
    "Lubica",
    "Eduard",
    "Jozef",
    "Vitazoslav, Klaudius",
    "Blahoslav",
    "Benadik",
    "Adrian",
    "Gabriel",
    "Marian",
    "Emanuel",
    "Alena",
    "Sona",
    "Miroslav",
    "Vieroslava",
    "Benjamin",
  }, { // april
    "Hugo",
    "Zita",
    "Richard",
    "Izidor",
    "Miroslava",
    "Irena",
    "Zoltan",
    "Albert",
    "Milena",
    "Igor",
    "Julius",
    "Estera",
    "Ales",
    "Justina",
    "Fedor",
    "Dana, Danica",
    "Rudolf, Rudolfa",
    "Valer",
    "Jela",
    "Marcel",
    "Ervin",
    "Slavomir",
    "Vojtech",
    "Juraj",
    "Marek",
    "Jaroslava",
    "Jaroslav",
    "Jarmila",
    "Lea",
    "Anastazia",
  }, { // maj
    "Sviatok prace",
    "Zigmund",
    "Galina, Timea",
    "Florian",
    "Lesia, Lesana",
    "Hermina",
    "Monika",
    "Ingrida",
    "Roland",
    "Viktoria",
    "Blazena",
    "Pankrac",
    "Servac",
    "Bonifac",
    "Zofia, Sofia",
    "Svetozar",
    "Gizela",
    "Viola",
    "Gertruda",
    "Bernard",
    "Zina",
    "Julia, Juliana",
    "Zelmira",
    "Ela",
    "Urban, Vivien",
    "Dusan",
    "Iveta",
    "Viliam",
    "Vilma",
    "Ferdinand",
    "Petrana, Petronela",
  }, { // jun
    "Zaneta",
    "Xenia, Oxana",
    "Karolina",
    "Lenka",
    "Laura",
    "Norbert",
    "Robert, Roberta",
    "Medard",
    "Stanislava",
    "Margareta, Greta",
    "Jesika",
    "Zlatko",
    "Anton",
    "Vasil",
    "Vit",
    "Blanka, Bianka",
    "Adolf",
    "Vratislav",
    "Alfred",
    "Valeria",
    "Alojz",
    "Paulina",
    "Sidonia",
    "Jan",
    "Olivia, Tadeas",
    "Adriana",
    "Ladislav, Ladislava",
    "Beata",
    "Peter, Pavol, Petra",
    "Melania",
  }, { // jul
    "Diana",
    "Berta",
    "Miloslav",
    "Prokop",
    "Cyril, Metod",
    "Patrik, Patricia",
    "Oliver",
    "Ivan",
    "Lujza",
    "Amalia",
    "Milota",
    "Nina",
    "Margita",
    "Kamil",
    "Henrich",
    "Drahomir, Drahomira, Rut",
    "Bohuslav",
    "Kamila",
    "Dusana",
    "Ilja, Elias",
    "Daniel",
    "Magdalena",
    "Olga",
    "Vladimir",
    "Jakub, Timur",
    "Anna, Hana, Anita, Aneta",
    "Bozena",
    "Kristof",
    "Marta",
    "Libusa",
    "Ignac",
  }, { // august
    "Bozidara",
    "Gustav",
    "Jergus",
    "Dominika, Dominik",
    "Hortenzia",
    "Jozefina",
    "Stefania",
    "Oskar",
    "Lubomira",
    "Vavrinec",
    "Zuzana",
    "Darina",
    "Lubomir",
    "Mojmir",
    "Marcela",
    "Leonard",
    "Milica",
    "Elena, Helena",
    "Lydia",
    "Anabela, Liliana",
    "Jana",
    "Tichomir",
    "Filip",
    "Bartolomej",
    "Ludovit",
    "Samuel",
    "Silvia",
    "Augustin",
    "Nikola, Nikolaj",
    "Ruzena",
    "Nora",
  }, { // september
    "Drahoslava",
    "Linda, Rebeka",
    "Belo",
    "Rozalia",
    "Regina",
    "Alica",
    "Marianna",
    "Miriama",
    "Martina",
    "Oleg",
    "Bystrik",
    "Maria, Marlena",
    "Ctibor",
    "Ludomil",
    "Jolana",
    "Ludmila",
    "Olympia",
    "Eugenia",
    "Konstantin",
    "Luboslav, Luboslava",
    "Matus",
    "Moric",
    "Zdenka",
    "Lubos, Lubor",
    "Vladislav, Vladislava",
    "Edita",
    "Cyprian",
    "Vaclav",
    "Michal, Michaela",
    "Jarolim",
  }, { // oktober
    "Arnold",
    "Levoslav",
    "Stela",
    "Frantisek",
    "Viera",
    "Natalia",
    "Eliska",
    "Brigita",
    "Dionyz",
    "Slavomira",
    "Valentina",
    "Maximilian",
    "Koloman",
    "Boris",
    "Terezia",
    "Vladimira",
    "Hedviga",
    "Lukas",
    "Kristian",
    "Vendelin",
    "Ursula",
    "Sergej",
    "Alojzia",
    "Kvetoslava",
    "Aurel",
    "Demeter",
    "Sabina",
    "Dobromila",
    "Klara",
    "Simon, Simona",
    "Aurelia",
  }, { // november
    "Denis, Denisa",
    "Hubert",
    "Karol",
    "Imrich",
    "Renata",
    "Rene",
    "Bohumir",
    "Teodor",
    "Tibor",
    "Martin, Maros",
    "Svatopluk",
    "Stanislav",
    "Irma",
    "Leopold",
    "Agnesa",
    "Klaudia",
    "Eugen",
    "Alzbeta",
    "Felix",
    "Elvira",
    "Cecilia",
    "Klement",
    "Emilia",
    "Katarina",
    "Kornel",
    "Milan",
    "Henrieta",
    "Vratko",
    "Ondrej, Andrej",
  }, { // december
    "Edmund",
    "Bibiana",
    "Oldrich",
    "Barbora, Barbara",
    "Oto",
    "Mikulas",
    "Ambroz",
    "Marina",
    "Izabela",
    "Raduz",
    "Hilda",
    "Otilia",
    "Lucia",
    "Branislava, Bronislava",
    "Ivica",
    "Albina",
    "Kornelia",
    "Slava",
    "Judita",
    "Dagmara",
    "Bohdan",
    "Adela",
    "Nadezda",
    "Adam, Eva",
    "Stefan",
    "Filomena",
    "Ivana, Ivona",
    "Milada",
    "David",
    "Silvester",
  }
};
